# Generated by Django 4.2.5 on 2024-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
