# Generated by Django 4.2.5 on 2024-02-02 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('storekeeper_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('storekeeper_approved_date', models.DateTimeField()),
                ('admin_approved_date', models.DateTimeField()),
                ('admin_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approved_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
                ('storekeeper_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stokeeper_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
