# Generated by Django 4.2.5 on 2024-02-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assignet_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignet_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
