# Generated by Django 4.2.5 on 2024-02-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_request_assignet_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='admin_approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='storekeeper_approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
